name: smart_finance_ai
description: A personal finance management app with AI-powered spending suggestions.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.0.5
  
  # UI packages
  cupertino_icons: ^1.0.5
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  
  # Others
  collection: ^1.17.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
