services:
  - type: web
    name: flutter-web-app
    env: node
    buildCommand: |
      # Install Flutter
      curl -fsSL https://storage.googleapis.com/download.flutter.io/flutter_linux_x64_stable.tar.xz -o flutter.tar.xz
      tar -xf flutter.tar.xz
      export PATH="$PWD/flutter/bin:$PATH"
      flutter doctor

      # Install dependencies and build Flutter Web app
      flutter pub get
      flutter build web

    startCommand: |
      # Serving the built Flutter Web app
      echo "Serving Flutter Web"
      cp -r build/web/* /usr/share/nginx/html/

    routes:
      - type: static
        path: /
        destination: /usr/share/nginx/html
