services:
  - type: web
    name: flutter-web-app
    env: node
    buildCommand: |
      # Install Flutter SDK
      curl -fsSL https://storage.googleapis.com/download.flutter.io/flutter_linux_x64_stable.tar.xz -o flutter.tar.xz
      tar -xf flutter.tar.xz
      export PATH="$PWD/flutter/bin:$PATH"
      flutter doctor

      # Install Flutter dependencies
      flutter pub get

      # Build Flutter web app
      flutter build web

    startCommand: |
      # Serve the Flutter web build using Nginx
      cp -r build/web/* /usr/share/nginx/html/

    routes:
      - type: static
        path: /
        destination: /usr/share/nginx/html
