# Use a base image that includes Flutter
FROM cirrusci/flutter:latest

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the local repo to the container's working directory
COPY . .

# Get dependencies
RUN flutter pub get

# Build the Flutter web app
RUN flutter build web

# Install a simple web server to serve the Flutter web app
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install http.server

# Expose the port the app will run on
EXPOSE 8000

# Start the server to serve the web app
CMD ["python3", "-m", "http.server", "8000"]
